version: '3.4'

x-default-environment:
  &default-environment
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: ant_wars
  MYSQL_USER: ant_wars_user
  MYSQL_PASSWORD: ant_wars_password
  MYSQL_HOST: db:3306

services:
  app:
    container_name: app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/ant-wars
    depends_on:
      - db
    links:
      - db
    environment:
      << : *default-environment
      FLASK_ENV: development
      PYTHONBREAKPOINT: ipdb.set_trace
      FLASK_ENV: development
      FLASK_APP: app/main.py
      FLASK_RUN_HOST: 0.0.0.0

  db:
    image: "mysql:latest"
    container_name: db
    ports:
      - "3306:3306"
    volumes:
       - mysql:/var/lib/mysql
    environment: *default-environment

volumes:
    mysql: {}
